from app.core.enums import AtsType, CollectionStrategy, ResumeVariant, VisaStatus

CANDIDATE = {
    "name": "Candidate",
    "current_title": "Senior Software Engineer",
    "years_experience": 7,
    "skills": [
        "React",
        "Next.js",
        "Vue",
        "Nuxt",
        "TypeScript",
        "JavaScript",
        "Tailwind",
        "MUI",
        "Vuetify",
        "Node.js",
        "Express",
        "NestJS",
        "Docker",
        "GitHub Actions",
        "GitLab CI",
        "Vite",
        "NX",
        "NPM",
        "Nexus",
        "MinIO",
        "PostgreSQL",
        "MongoDB",
        "MySQL",
        "Redis",
        "REST",
        "GraphQL",
        "WebSockets",
        "MQTT",
        "Swagger",
        "Service Workers",
        "PWA",
        "Firebase",
        "SignalR",
        "Sentry",
    ],
    "target_roles": [
        "Senior Software Engineer",
        "Senior Full Stack Engineer",
        "Senior Frontend Engineer",
        "Staff Software Engineer",
        "Tech Lead",
    ],
    "target_countries": ["AE", "DE", "NL", "IE", "SA", "SE", "DK", "FI", "NO", "EE", "PT", "CA"],
    "preferred_countries": ["AE", "DE", "NL", "IE", "SA", "SE", "DK", "FI", "NO", "EE", "PT", "CA"],
    "visa_required": True,
    "relocation_required": True,
    "english_level": "professional",
    "salary_preferences": {},
    "additional_preferences": {
        "requires_sponsorship": True,
        "nationality": "IR",
    },
}

RESUMES = [
    {
        "variant": ResumeVariant.SENIOR_SOFTWARE_ENGINEER.value,
        "title": "Senior Software Engineer",
        "is_default": True,
        "skills": CANDIDATE["skills"],
        "content": (
            "Senior Software Engineer with 7+ years building production web applications. "
            "Works across frontend (React, Next.js, Vue, Nuxt, TypeScript) and backend "
            "(Node.js, Express, NestJS) with PostgreSQL, MongoDB, MySQL, Redis, Docker, and CI/CD. "
            "Requires visa sponsorship and relocation support. "
            "Target countries: UAE, Germany, Netherlands, Ireland, Saudi Arabia, Sweden, "
            "Denmark, Finland, Norway, Estonia, Portugal, Canada."
        ),
    },
    {
        "variant": ResumeVariant.SENIOR_FRONTEND_ENGINEER.value,
        "title": "Senior Frontend Engineer",
        "is_default": False,
        "skills": [
            "React",
            "Next.js",
            "Vue",
            "Nuxt",
            "TypeScript",
            "JavaScript",
            "Tailwind",
            "MUI",
            "Vuetify",
            "PWA",
            "Service Workers",
        ],
        "content": (
            "Senior Frontend Engineer with 7+ years delivering production UIs in React, Next.js, "
            "Vue, and Nuxt, with TypeScript, Tailwind, MUI, and Vuetify. Comfortable with PWAs, "
            "service workers, and consuming REST/GraphQL APIs. Requires visa sponsorship and relocation."
        ),
    },
    {
        "variant": ResumeVariant.FULL_STACK_ENGINEER.value,
        "title": "Senior Full Stack Engineer",
        "is_default": False,
        "skills": [
            "React",
            "Next.js",
            "TypeScript",
            "Node.js",
            "NestJS",
            "Express",
            "PostgreSQL",
            "Redis",
            "Docker",
        ],
        "content": (
            "Senior Full Stack Engineer with 7+ years spanning React/Next.js frontends and "
            "Node.js/NestJS/Express backends, PostgreSQL/Redis, and Docker-based delivery. "
            "Requires visa sponsorship and relocation support."
        ),
    },
]

# Only attach a public collector when the board/feed was verified live.
# Companies without a public ATS JSON/XML feed are stored for later, visa UNKNOWN.
COMPANIES = [
    {
        "slug": "careem",
        "name": "Careem",
        "country": "AE",
        "city": "Dubai",
        "ats_type": AtsType.GREENHOUSE.value,
        "board_token": "careem",
        "careers_url": "https://boards.greenhouse.io/careem",
        "priority": 100,
        "aliases": ["Careem Networks"],
    },
    {
        "slug": "property-finder",
        "name": "Property Finder",
        "country": "AE",
        "city": "Dubai",
        "ats_type": AtsType.CAREER_PAGE.value,
        "board_token": None,
        "careers_url": "https://www.propertyfinder.ae/careers",
        "priority": 90,
        "aliases": ["Propertyfinder"],
        "enabled": True,
    },
    {
        "slug": "revolut",
        "name": "Revolut",
        "country": "AE",
        "city": "Dubai",
        "ats_type": AtsType.CAREER_PAGE.value,
        "board_token": None,
        "careers_url": "https://www.revolut.com/careers/",
        "priority": 95,
        "aliases": [],
    },
    {
        "slug": "kitopi",
        "name": "Kitopi",
        "country": "AE",
        "city": "Dubai",
        "ats_type": AtsType.CAREER_PAGE.value,
        "board_token": None,
        "careers_url": "https://kitopi.com/careers",
        "priority": 80,
        "aliases": [],
    },
    {
        "slug": "delivery-hero",
        "name": "Delivery Hero",
        "country": "DE",
        "city": "Berlin",
        "ats_type": AtsType.CAREER_PAGE.value,
        "board_token": None,
        "careers_url": "https://careers.deliveryhero.com/",
        "priority": 98,
        "aliases": ["DeliveryHero"],
    },
    {
        "slug": "zalando",
        "name": "Zalando",
        "country": "DE",
        "city": "Berlin",
        "ats_type": AtsType.CAREER_PAGE.value,
        "board_token": None,
        "careers_url": "https://jobs.zalando.com/",
        "priority": 92,
        "aliases": ["Zalando SE"],
    },
    {
        "slug": "n26",
        "name": "N26",
        "country": "DE",
        "city": "Berlin",
        "ats_type": AtsType.GREENHOUSE.value,
        "board_token": "n26",
        "careers_url": "https://boards.greenhouse.io/n26",
        "priority": 96,
        "aliases": ["N26 Bank"],
    },
    {
        "slug": "sap",
        "name": "SAP",
        "country": "DE",
        "city": "Walldorf",
        "ats_type": AtsType.CAREER_PAGE.value,
        "board_token": None,
        "careers_url": "https://jobs.sap.com/",
        "priority": 70,
        "aliases": ["SAP SE"],
    },
    {
        "slug": "personio",
        "name": "Personio",
        "country": "DE",
        "city": "Munich",
        "ats_type": AtsType.PERSONIO_XML.value,
        "board_token": "personio",
        "careers_url": "https://www.personio.com/about-personio/careers/",
        "priority": 88,
        "aliases": [],
    },
    {
        "slug": "adyen",
        "name": "Adyen",
        "country": "NL",
        "city": "Amsterdam",
        "ats_type": AtsType.GREENHOUSE.value,
        "board_token": "adyen",
        "careers_url": "https://boards.greenhouse.io/adyen",
        "priority": 97,
        "aliases": ["Adyen N.V."],
    },
    {
        "slug": "booking",
        "name": "Booking.com",
        "country": "NL",
        "city": "Amsterdam",
        "ats_type": AtsType.CAREER_PAGE.value,
        "board_token": None,
        "careers_url": "https://jobs.booking.com/",
        "priority": 94,
        "aliases": ["Booking"],
    },
    {
        "slug": "picnic",
        "name": "Picnic",
        "country": "NL",
        "city": "Amsterdam",
        "ats_type": AtsType.GREENHOUSE.value,
        "board_token": "teampicnic",
        "careers_url": "https://job-boards.greenhouse.io/teampicnic",
        "priority": 85,
        "aliases": ["Picnic Technologies"],
    },
    {
        "slug": "intercom",
        "name": "Intercom",
        "country": "IE",
        "city": "Dublin",
        "ats_type": AtsType.GREENHOUSE.value,
        "board_token": "intercom",
        "careers_url": "https://boards.greenhouse.io/intercom",
        "priority": 93,
        "aliases": [],
    },
    {
        "slug": "hubspot",
        "name": "HubSpot",
        "country": "IE",
        "city": "Dublin",
        "ats_type": AtsType.GREENHOUSE.value,
        "board_token": "hubspotjobs",
        "careers_url": "https://boards.greenhouse.io/hubspotjobs",
        "priority": 91,
        "aliases": [],
    },
    {
        "slug": "bolt",
        "name": "Bolt",
        "country": "EE",
        "city": "Tallinn",
        "ats_type": AtsType.CAREER_PAGE.value,
        "board_token": None,
        "careers_url": "https://bolt.eu/en/careers/",
        "priority": 84,
        "aliases": ["Bolt Technology"],
    },
    {
        "slug": "pipedrive",
        "name": "Pipedrive",
        "country": "EE",
        "city": "Tallinn",
        "ats_type": AtsType.LEVER.value,
        "board_token": "pipedrive",
        "careers_url": "https://jobs.lever.co/pipedrive",
        "priority": 75,
        "aliases": [],
        # Do not mark sponsorship as confirmed. Current public evidence is not used to invent a claim.
        "visa_status": VisaStatus.UNKNOWN.value,
    },
]

def _source(
    name: str,
    description: str,
    strategy: CollectionStrategy,
    *,
    implemented: bool,
    phase: int,
    docs_url: str | None = None,
) -> dict:
    return {
        "name": name,
        "description": description,
        "ats_type": name,
        "collection_strategy": strategy.value,
        "adapter_implemented": implemented,
        "roadmap_phase": phase,
        "docs_url": docs_url,
    }


# Catalog of every ATS the project can recognise. `adapter_implemented` is what
# the coverage report uses to show where the next adapter is worth building.
JOB_SOURCES = [
    _source(
        AtsType.GREENHOUSE.value,
        "Greenhouse job board API",
        CollectionStrategy.API,
        implemented=True,
        phase=1,
        docs_url="https://developers.greenhouse.io/job-board.html",
    ),
    _source(
        AtsType.LEVER.value,
        "Lever postings API",
        CollectionStrategy.API,
        implemented=True,
        phase=1,
        docs_url="https://github.com/lever/postings-api",
    ),
    _source(
        AtsType.PERSONIO_XML.value,
        "Personio public XML feed",
        CollectionStrategy.XML,
        implemented=True,
        phase=1,
    ),
    _source(
        AtsType.ASHBY.value,
        "Ashby public job board API",
        CollectionStrategy.API,
        implemented=True,
        phase=1,
        docs_url="https://developers.ashbyhq.com/reference/postingapi",
    ),
    _source(
        AtsType.SMARTRECRUITERS.value,
        "SmartRecruiters public postings API",
        CollectionStrategy.API,
        implemented=True,
        phase=1,
        docs_url="https://developers.smartrecruiters.com/reference/postingapisearch",
    ),
    _source(
        AtsType.WORKABLE.value,
        "Workable public account feed",
        CollectionStrategy.API,
        implemented=True,
        phase=1,
    ),
    _source(
        AtsType.RECRUITEE.value,
        "Recruitee public offers feed",
        CollectionStrategy.API,
        implemented=True,
        phase=2,
    ),
    _source(
        AtsType.TEAMTAILOR.value,
        "Teamtailor careers RSS feed",
        CollectionStrategy.XML,
        implemented=True,
        phase=2,
    ),
    _source(
        AtsType.WORKDAY.value,
        "Workday CXS job search API (needs tenant and site id)",
        CollectionStrategy.API,
        implemented=True,
        phase=2,
    ),
    _source(
        AtsType.COMEET.value,
        "Comeet careers API (per-company token required)",
        CollectionStrategy.API,
        implemented=False,
        phase=3,
    ),
    _source(
        AtsType.JOBVITE.value,
        "Jobvite careers site",
        CollectionStrategy.HTML,
        implemented=False,
        phase=3,
    ),
    _source(
        AtsType.BAMBOOHR.value,
        "BambooHR careers list",
        CollectionStrategy.JSON,
        implemented=False,
        phase=3,
    ),
    _source(
        AtsType.ICIMS.value,
        "iCIMS portal (session based)",
        CollectionStrategy.BROWSER,
        implemented=False,
        phase=4,
    ),
    _source(
        AtsType.TALEO.value,
        "Oracle Taleo portal",
        CollectionStrategy.BROWSER,
        implemented=False,
        phase=4,
    ),
    _source(
        AtsType.SUCCESSFACTORS.value,
        "SAP SuccessFactors (credentialed OData API)",
        CollectionStrategy.BROWSER,
        implemented=False,
        phase=4,
    ),
    _source(
        AtsType.CUSTOM.value,
        "Bespoke company jobs API",
        CollectionStrategy.HTML,
        implemented=False,
        phase=4,
    ),
    _source(
        AtsType.CAREER_PAGE.value,
        "HTML careers page with no public feed",
        CollectionStrategy.BROWSER,
        implemented=False,
        phase=4,
    ),
    _source(
        AtsType.UNKNOWN.value,
        "ATS not identified yet",
        CollectionStrategy.NONE,
        implemented=False,
        phase=0,
    ),
]
